apiVersion: v1
kind: Template
labels:
  template: elasticsearch-ephemeral-template
message: :-
  The following service(s) have been created in your project: ${ELASTICSEARCH_SERVICE_NAME}.

   Connection URL: http://${ELASTICSEARCH_SERVICE_NAME}:9200/
metadata:
  annotations:
    description: |-
      Elasticsearch database service, without persistent storage.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    iconClass: icon-elastic
    openshift.io/display-name: Elasticsearch (Ephemeral)
    tags: database,elasticsearch
    template.openshift.io/documentation-url: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/index.html
    template.openshift.io/long-description: This template provides a standalone Elasticsearch
      server with a database created.  The database is not stored on persistent storage,
      so any restart of the service will result in all data being lost.
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: elasticsearch-ephemeral
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${ELASTICSEARCH_SERVICE_NAME}
  spec:
    ports:
    - name: restapi
      protocol: TCP
      port: 9200
      targetPort: 9200
    selector:
      name: ${ELASTICSEARCH_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${ELASTICSEARCH_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${ELASTICSEARCH_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${ELASTICSEARCH_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env: {}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 9200
            timeoutSeconds: 1
          name: elasticsearch
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: ${ELASTICSEARCH_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ""
          name: ${ELASTICSEARCH_SERVICE_NAME}-data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - elasticsearch
        from:
          kind: ImageStreamTag
          name: ocp-elasticsearch:${ELASTICSEARCH_VERSION}
          namespace: ${NAMESPACE}
        lastTriggerImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for this instance.
  displayName: Elasticsearch Service Name
  name: ELASTICSEARCH_SERVICE_NAME
  required: true
  value: elasticsearch
- description:: Version of Elasticsearch image to be used (5.5, 5.6, or latest).
  displayName: Version of Elasticsearch Image
  name: ELASTICSEARCH_VERSION
  required: true
  value: "5.6"
